In [2]:
import pandas as pd
import numpy as np
heart_df= pd.read_csv("C:/Users/shaih/Downloads/data_type_of_heart_faliure.csv")

In [3]:
heart_df=pd.DataFrame(heart_df)
heart_df.describe()
labels = heart_df.drop(['type_of_heart_failure','inpatient_number'],axis=1).copy().columns
X=heart_df[labels]
y=heart_df['type_of_heart_failure']
#y=y.to_numpy()
#X=X.to_numpy()
##print(X)
##df1 = pd.concat(g.sample(2) for idx, g in heart_df.groupby('labels'))

In [4]:
heart_df.describe()
heart_df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2008 entries, 0 to 2007
Data columns (total 57 columns):
 #   Column                                          Non-Null Count  Dtype  
---  ------                                          --------------  -----  
 0   Unnamed: 0                                      2008 non-null   int64  
 1   inpatient_number                                2008 non-null   int64  
 2   DestinationDischarge_DIED                       2008 non-null   int64  
 3   DestinationDischarge_HealthcareFacility         2008 non-null   int64  
 4   DestinationDischarge_HOME                       2008 non-null   int64  
 5   admission_ward_ICU                              2008 non-null   int64  
 6   admission_ward_GENERAL_WARD                     2008 non-null   int64  
 7   admission_ward_CARDIOLOGY                       2008 non-null   int64  
 8   admission_way                                   2008 non-null   int64  
 9   discharge_department_ICU                 

In [40]:
from sklearn.model_selection import train_test_split
X1=X[labels[:40]]
X_train, X_test, y_train, y_test = train_test_split(X1, y, random_state=2)
print (X_train.shape, y_train.shape)
print(X1)
print(y_test)

(1506, 40) (1506,)
      Unnamed: 0  DestinationDischarge_DIED  \
0              1                          0   
1              2                          0   
2              3                          0   
3              4                          0   
4              5                          0   
...          ...                        ...   
2003        2004                          0   
2004        2005                          0   
2005        2006                          0   
2006        2007                          0   
2007        2008                          0   

      DestinationDischarge_HealthcareFacility  DestinationDischarge_HOME  \
0                                           0                          1   
1                                           0                          1   
2                                           0                          1   
3                                           0                          1   
4                                   

In [6]:
X_train.head()

Unnamed: 0  DestinationDischarge_DIED  \
1623        1624                          0   
748          749                          0   
71            72                          0   
1881        1882                          0   
1137        1138                          0   

      DestinationDischarge_HealthcareFacility  DestinationDischarge_HOME  \
1623                                        1                          0   
748                                         0                          1   
71                                          1                          0   
1881                                        1                          0   
1137                                        0                          0   

      admission_ward_ICU  admission_ward_GENERAL_WARD  \
1623                   0                            0   
748                    0                            0   
71                     0                            0   
1881                   0                            0   
1137                   0                            0   

      admission_ward_CARDIOLOGY  admission_way  discharge_department_ICU  \
1623                          1              1                         0   
748                           1              1                         0   
71                            1              0                         0   
1881                          1              1                         0   
1137                          1              0                         0   

      discharge_department_GENERAL_WARD  ...  connective_tissue_disease  \
1623                                  0  ...                          0   
748                                   0  ...                          0   
71                                    0  ...                          0   
1881                                  0  ...                          0   
1137                                  0  ...                          0   

      diabetes  hemiplegia  leukemia  malignant_lymphoma  solid_tumor  AIDS  \
1623         0           0         0                   0            0     0   
748          0           0         0                   0            0     0   
71           0           0         0                   0            0     0   
1881         0           0         0                   0            0     0   
1137         1           0         0                   0            0     0   

      type_II_respiratory_failure  consciousness  eye_opening  
1623                            1              1            4  
748                             0              1            4  
71                              0              1            4  
1881                            0              1            4  
1137                            0              1            4  

[5 rows x 40 columns]

In [7]:
y_train.head()

1623    2
748     3
71      3
1881    3
1137    3
Name: type_of_heart_failure, dtype: int64

In [8]:
from sklearn import datasets, linear_model
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold
clf=RandomForestClassifier(random_state=2)
clf.fit(X_train, y_train)
model=clf.fit(X_train, y_train)
cross_val_score(clf, X_train, y_train, cv=5,error_score="raise")
y_pred=model.predict(X_test)

In [9]:
from sklearn.metrics import confusion_matrix
from matplotlib import pyplot as plt

conf_mat = confusion_matrix(y_true=y_test, y_pred=y_pred)
print('Confusion matrix:\n', conf_mat)

Confusion matrix:
 [[  0   4   9]
 [  0  48  71]
 [  0  28 342]]


In [10]:
#Duplicate sampling

In [11]:
#Duplicate sampling
import imblearn 
from sklearn.datasets import make_classification
from imblearn.over_sampling import RandomOverSampler


In [12]:
#making boolean seireis for a team name
Both = y_train==3
Right = y_train ==1
Left = y_train ==2

In [13]:
#create heart_df_Both,Left,Right
heart_df=heart_df.rename(columns={"Unnamed: 0": "Unnamed"})
X_train=X_train.rename(columns={"Unnamed: 0": "Unnamed"})
heart_df_Both=heart_df.loc[heart_df['type_of_heart_failure']==3]
heart_df_Left=heart_df.loc[heart_df['type_of_heart_failure']==2]
heart_df_Right=heart_df.loc[heart_df['type_of_heart_failure']==1]
print(heart_df_Right.describe)
print(heart_df_Left.describe)
print(heart_df_Both.describe)

<bound method NDFrame.describe of       Unnamed  inpatient_number  DestinationDischarge_DIED  \
25         26            818671                          0   
230       231            777291                          0   
450       451            747991                          0   
468       469            805815                          0   
502       503            792850                          0   
504       505            849047                          0   
508       509            805113                          0   
518       519            812004                          0   
519       520            808366                          0   
521       522            770733                          0   
530       531            827105                          0   
534       535            770173                          0   
538       539            750142                          0   
764       765            795309                          0   
928       929            758191     

In [14]:
#filtering only both rows
common = X_train.merge(heart_df_Both,on=['Unnamed'],how='inner')
#print(common)
Both_train=X_train[(~X_train.Unnamed.isin(common.Unnamed))]
print(X_train.shape)
print(heart_df_Both.shape)
print(common.shape)
common_train=X_train[X_train["Unnamed"].isin(common["Unnamed"])]
print(common_train)

(1506, 40)
(1480, 57)
(1110, 96)
      Unnamed  DestinationDischarge_DIED  \
748       749                          0   
71         72                          0   
1881     1882                          0   
1137     1138                          0   
1840     1841                          0   
...       ...                        ...   
360       361                          0   
466       467                          0   
299       300                          0   
493       494                          0   
527       528                          0   

      DestinationDischarge_HealthcareFacility  DestinationDischarge_HOME  \
748                                         0                          1   
71                                          1                          0   
1881                                        1                          0   
1137                                        0                          0   
1840                                        0             

In [15]:
#filtering only Left rows
commonL = X_train.merge(heart_df_Left,on=['Unnamed'],how='inner')
print(X_train.shape)
print(heart_df_Left.shape)
Left_train=X_train[(~X_train.Unnamed.isin(commonL.Unnamed))]
print(commonL.shape)
commonL_train=X_train[X_train["Unnamed"].isin(commonL["Unnamed"])]
print(commonL_train)
#print(Left_train)

(1506, 40)
(477, 57)
(358, 96)
      Unnamed  DestinationDischarge_DIED  \
1623     1624                          0   
1209     1210                          0   
1932     1933                          0   
1841     1842                          0   
1462     1463                          0   
...       ...                        ...   
1287     1288                          0   
1099     1100                          0   
1558     1559                          0   
1608     1609                          0   
1192     1193                          0   

      DestinationDischarge_HealthcareFacility  DestinationDischarge_HOME  \
1623                                        1                          0   
1209                                        0                          0   
1932                                        0                          1   
1841                                        0                          1   
1462                                        0               

In [16]:
#filtering only Right rows
commonR = X_train.merge(heart_df_Right,on=['Unnamed'],how='inner')
#print(commonR)
Right_train=X_train[(~X_train.Unnamed.isin(commonR.Unnamed))]
print(X_train.shape)
print(heart_df_Right.shape)
print(commonR.shape)
commonR_train=X_train[X_train["Unnamed"].isin(commonR["Unnamed"])]
print(commonR_train)
#print(Right_train)

(1506, 40)
(51, 57)
(38, 96)
      Unnamed  DestinationDischarge_DIED  \
1556     1557                          0   
932       933                          0   
1606     1607                          0   
508       509                          0   
504       505                          0   
530       531                          0   
943       944                          0   
519       520                          0   
928       929                          0   
1438     1439                          0   
1654     1655                          0   
1423     1424                          0   
1471     1472                          0   
1514     1515                          0   
518       519                          0   
521       522                          0   
1459     1460                          0   
967       968                          0   
1489     1490                          0   
1775     1776                          0   
1719     1720                          0   
143

In [17]:
X_train.to_csv("X_train_cross_Validation.csv")
y_train.to_csv("y_train_cross_Validation.csv")
X_test.to_csv("X_test_cross_Validation.csv")
y_test.to_csv("y_test_cross_Validation.csv")

In [20]:
#data_frame with all columns and classes
common_all=pd.concat([commonL,common,commonR])
print(common)

      Unnamed  DestinationDischarge_DIED_x  \
0         749                            0   
1          72                            0   
2        1882                            0   
3        1138                            0   
4        1841                            0   
...       ...                          ...   
1105      361                            0   
1106      467                            0   
1107      300                            0   
1108      494                            0   
1109      528                            0   

      DestinationDischarge_HealthcareFacility_x  DestinationDischarge_HOME_x  \
0                                             0                            1   
1                                             1                            0   
2                                             1                            0   
3                                             0                            0   
4                                             0

In [21]:
#under-sampling
#value_counts is descending (bigger to smaller)
count_Both, count_Left, count_Right =common_all.type_of_heart_failure.value_counts()

print(count_Both)
print(count_Left)
print(count_Right)
#Divided by class (commonL, commonR, common)
commonL_under=commonL.sample(count_Right)
common_under=common.sample(count_Right)
#testing
X_test_under=pd.concat([commonL_under,common_under,commonR], axis=0)
print('random_under-sampling')
print(X_test_under.type_of_heart_failure.value_counts())

1110
358
38
random_under-sampling
1    38
2    38
3    38
Name: type_of_heart_failure, dtype: int64


In [86]:
#Under-sampling
from imblearn.under_sampling import RandomUnderSampler 
rus = RandomUnderSampler(sampling_strategy='majority',random_state=2)
def confusion_matrix_Under(X_train,y_train,X_test,y_test):
    X_train_under, y_train_under = rus.fit_resample(X_train, y_train)
    under=model.fit(X_train_under, y_train_under)
    print ('Random-Under-Sampling result')
    y_pred_under=under.predict(X_test)
    print(y_pred_under) 
    conf_matrix_under = confusion_matrix(y_true=y_test, y_pred=y_pred_under)
    print('Confusion matrix ada:\n', conf_matrix_under)
    kappa_under= cohen_kappa_score(y_test,y_pred_under, labels=None, weights='quadratic', sample_weight=None)
    print('kappa under')
    print(kappa_under)

confusion_matrix_Under(X_train,y_train,X_test,y_test)

Random-Under-Sampling result
[2 2 2 1 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 3 2 2 2 2 3 2 2 2 2 3 2 2 2 2 2
 2 2 3 2 2 2 2 2 2 2 2 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 2 2 2 2 2 2
 2 2 2 2 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 2 2 2 2 2 2 2 2 2 2
 2 3 2 2 2 2 2 2 2 2 2 2 2 3 2 3 2 2 2 3 2 3 2 2 2 3 2 2 2 2 3 2 2 2 2 2 3
 3 2 2 2 2 2 3 2 2 2 2 2 2 2 2 2 2 2 2 2 3 2 2 2 2 2 3 2 2 2 2 2 2 2 2 2 2
 2 1 2 2 2 2 2 2 2 2 2 2 2 3 1 2 2 2 2 2 2 2 2 2 3 2 2 3 2 2 2 2 2 2 3 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 2 2 2 2 2 2 2
 2 2 2 2 2 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 3 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 

In [77]:
#random over-sampling
commonL_over=commonL.sample(count_Both, replace=True)
commonR_over=commonR.sample(count_Both, replace=True)

#testing
X_test_over=pd.concat([commonL_over,common,commonR_over], axis=0)
print('random_over-sampling')
print(X_test_over.type_of_heart_failure.value_counts())


from imblearn.over_sampling import RandomOverSampler
#ros=RandomOverSampler()
#X_ros, y_ros= ros.fit_sample(X_train,y_train)
#fit(X_train,y_train)

random_over-sampling
2    1110
1    1110
3    1110
Name: type_of_heart_failure, dtype: int64


In [85]:
#Over-sampling
from imblearn.over_sampling import RandomOverSampler 
ros = RandomOverSampler(sampling_strategy='minority',random_state=2)
def confusion_matrix_Over(X_train,y_train,X_test,y_test):
    X_train_over, y_train_over = ros.fit_resample(X_train, y_train)
    over=model.fit(X_train_over, y_train_over)
    print ('Random-Over-Sampling result')
    y_pred_over=over.predict(X_test)
    print(y_pred_over) 
    conf_matrix_over = confusion_matrix(y_true=y_test, y_pred=y_pred_over)
    print('Confusion matrix ada:\n', conf_matrix_under)
    kappa_over= cohen_kappa_score(y_test,y_pred_over, labels=None, weights='quadratic', sample_weight=None)
    print('kappa over')
    print(kappa_over)

confusion_matrix_Over(X_train,y_train,X_test,y_test)

Random-Over-Sampling result
[3 3 3 3 3 3 3 3 3 3 3 3 2 2 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 2 2 2 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 3 2
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 2 3 2 3 3 3 3 3 3 3 3 2 3 3 2 3 3 3
 3 2 3 3 2 3 3 3 3 3 3 3 3 2 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3
 3 3 3 2 3 3 3 3 3 3 3 3 2 3 3 2 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 2 3 3 3 3 3 3 3 2 3 2 2 3 3 3 3 3 2 3 3 3
 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3
 2 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 2 3 3 3 3 2 3 3 2 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 2 3 3 3 2 3 3 3 3
 3 2 2 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 3 3 2 2 3 3 2 3 3 3 3 3 3 3 3 3 3 3
 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 2 2

In [50]:
#syntesing and over-sampling
#SMOTE
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.metrics import cohen_kappa_score, make_scorer
def confusion_matrix_SMOTE(X_train,y_train,X_test,y_test):
    sm= SMOTE(random_state=2)
    X_train_SMOTE, y_train_SMOTE= sm.fit_resample(X_train, y_train)
#print(X_train_res.head)
#print(y_train_res.head)
    model.fit(X_train_SMOTE, y_train_SMOTE)
    print ('SMOTE result')
    y_pred_SMOTE=model.predict(X_test)
    print(y_pred_SMOTE) 
    conf_mat_SMOTE = confusion_matrix(y_true=y_test, y_pred=y_pred_SMOTE)
    print('Confusion matrix SMOTE:\n', conf_mat_SMOTE)
    kappa_SMOTE= cohen_kappa_score(y_test,y_pred_SMOTE, labels=None, weights='quadratic', sample_weight=None)
    print('kappa SMOTE')
    print(kappa_SMOTE)
    

confusion_matrix_SMOTE(X_train,y_train,X_test,y_test)

Cross_validation
SMOTE result
[3 3 2 3 3 3 3 3 3 3 2 3 2 2 3 3 3 3 2 2 3 3 3 2 3 2 3 3 3 3 3 3 3 3 3 2 3
 3 2 3 2 2 2 3 2 3 2 1 3 2 3 3 3 3 3 3 3 3 3 3 2 2 3 2 3 3 3 3 3 3 2 3 2 2
 3 2 3 3 3 2 3 3 3 3 2 3 2 2 3 2 2 3 3 3 3 3 3 2 2 3 3 3 2 3 3 2 2 3 3 3 3
 2 2 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 2 2 2 2 2 3 3 3 3 3 3 2 2 3 2 3 2 3
 3 2 3 2 2 1 3 3 3 3 3 3 3 2 2 2 3 3 3 2 2 2 3 2 3 3 3 3 3 3 3 2 2 3 2 3 3
 3 3 3 2 3 3 3 3 3 3 3 2 2 3 3 2 2 3 2 3 3 3 2 3 3 3 3 2 3 2 2 3 3 3 3 3 3
 3 3 3 3 3 2 3 3 3 3 2 2 3 3 2 3 2 2 2 3 3 3 3 3 2 3 2 2 3 3 3 2 3 2 3 3 3
 3 3 3 2 3 3 3 2 3 3 3 3 3 2 3 3 3 3 2 2 3 3 2 3 3 3 3 3 3 2 2 3 2 2 3 3 2
 3 3 3 2 3 3 3 2 3 3 3 3 2 3 3 2 3 2 2 3 3 3 3 3 3 2 2 3 3 2 2 3 3 3 3 2 3
 3 3 3 2 3 3 3 3 2 3 3 3 3 3 3 3 2 3 3 3 3 3 3 1 3 2 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 2 3 2 3 3 2 3 3 2 3 3 3 3 2 2 3 3 3 3 2 3 2 2 3 2 3 3 3 2 3 3 3 2
 3 2 2 3 3 3 2 3 3 3 2 2 3 3 3 3 3 3 3 3 3 2 2 3 3 2 3 3 3 3 3 3 3 3 3 3 3
 2 3 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 2 3 3 3 3 2 3 3 3 3 3 3 3 2

In [88]:
#SMOTEENN - combine over&under samoling
from imblearn.combine import SMOTEENN

def confusion_matrix_SMOTEENN(X_train,y_train,X_test,y_test):
    sme= SMOTEENN(random_state=2)
    X_train_SMOTEENN, y_train_SMOTEENN= sme.fit_resample(X_train, y_train)
    model.fit(X_train_SMOTEENN, y_train_SMOTEENN)
    print ('SMOTEENN result')
    y_pred_SMOTEENN=model.predict(X_test)
    print(y_pred_SMOTEENN) 
    conf_mat_SMOTEENN = confusion_matrix(y_true=y_test, y_pred=y_pred_SMOTEENN)
    print('Confusion matrix SMOTEENN:\n', conf_mat_SMOTEENN)
    kappa_SMOTEENN= cohen_kappa_score(y_test,y_pred_SMOTEENN, labels=None, weights='quadratic', sample_weight=None)
    print('kappa SMOTEENN')
    print(kappa_SMOTEENN)
    

confusion_matrix_SMOTEENN(X_train,y_train,X_test,y_test)

SMOTEENN result
[3 2 2 1 2 2 2 3 3 3 2 3 2 2 3 3 3 2 2 2 3 3 3 2 3 2 3 2 3 3 2 3 3 2 3 2 3
 3 2 3 2 2 2 2 2 3 2 1 3 2 3 3 2 3 3 3 3 3 2 3 2 2 2 2 3 3 2 2 2 2 2 3 2 2
 3 2 3 3 3 2 2 3 3 3 2 3 2 2 3 2 2 3 3 3 3 3 3 2 2 3 3 3 2 1 2 2 2 3 2 3 2
 2 2 3 2 3 3 3 3 3 3 3 2 2 3 3 3 3 3 2 2 2 2 2 2 3 3 3 3 2 3 2 2 3 2 3 2 2
 2 2 2 2 2 1 3 3 2 3 3 2 3 2 2 2 3 3 3 2 2 2 3 1 3 3 3 2 3 3 3 2 2 3 2 3 3
 2 3 3 2 3 2 2 3 2 2 3 2 2 3 3 2 2 3 2 2 3 3 2 2 3 3 3 2 3 2 2 2 1 3 3 3 3
 2 3 3 2 3 2 3 3 3 2 2 2 3 3 2 3 2 2 2 3 2 3 3 3 2 3 2 2 2 2 3 2 3 2 3 2 3
 3 1 3 2 3 2 3 2 3 2 3 3 3 2 2 3 3 3 2 2 3 2 2 3 3 3 3 3 3 2 2 3 2 2 2 2 2
 2 3 3 2 3 3 3 2 3 3 2 2 2 3 3 2 3 2 2 3 3 3 2 2 3 2 2 3 2 2 2 3 3 2 3 2 3
 2 3 2 2 2 3 3 3 2 3 3 3 3 3 3 2 2 2 2 3 3 3 3 1 3 2 3 3 3 3 2 3 3 3 2 3 3
 3 2 3 3 2 3 2 2 2 2 2 3 2 3 3 3 2 2 2 3 3 3 2 2 3 2 2 2 2 2 2 3 2 2 2 3 2
 3 2 2 2 2 2 2 3 3 3 2 2 2 3 2 1 2 3 3 3 3 2 2 2 2 2 3 3 3 3 2 2 3 3 3 2 3
 2 3 2 2 2 3 3 2 3 2 3 3 2 3 3 2 3 2 3 3 3 2 3 3 2 2 2 3 3 2 2 3 2 3 2 2 3
 3 2 2 3 

In [89]:
#ADASYN
from imblearn.over_sampling import ADASYN
ada= ADASYN(sampling_strategy='minority',random_state=2,n_neighbors=5)
def confusion_matrix_ADASYN(X_train,y_train,X_test,y_test):
    X_train_ada, y_train_ada=ada.fit_resample(X_train,y_train)
    l=model.fit(X_train_ada, y_train_ada)
    print ('ADASYN result')
    y_pred_ada=l.predict(X_test)
    print(y_pred_ada) 
    conf_matrix_ada = confusion_matrix(y_true=y_test, y_pred=y_pred_ada)
    print('Confusion matrix ada:\n', conf_matrix_ada)
    kappa_ada= cohen_kappa_score(y_test,y_pred_ada, labels=None, weights='quadratic', sample_weight=None)
    print('kappa ada')
    print(kappa_ada)
    
print('Cross_validation')    
confusion_matrix_ADASYN(X_train,y_train,X_test,y_test)

Cross_validation
ADASYN result
[3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 3 2 3
 3 3 3 3 2 3 3 3 3 3 1 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 2 2
 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 1 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 2 3 2 3 3 3 3 2 3
 3 2 3 3 2 1 3 3 3 3 3 3 3 2 3 1 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 2 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 2 3 3 1 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 2 3 2 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 2 3 2 3 3 3 3 3 3 3 3 3 2 3 3 2 3 3 3 3 3 3 3 3 3 2 3 3 3 3
 3 3 3 2 3 3 3 2 3 3 3 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 2 3 3 3 3 3 3 3
 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 1 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 2 3 3 2 3 3 3 3 2 3 3 3 3 3 2 3 2 3 3 2 3 3 3 3 3 2 3 2
 3 2 2 3 3 3 3 3 3 3 3 2 3 3 3 1 3 3 3 3 3 3 1 3 3 2 3 3 3 3 3 3 3 3 3 3 3
 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 

In [90]:
#ADASYN- only minority&majority the same result as regular x_train,y_train
X_train_minority=heart_df_Right[:40]
X_train_majority=heart_df_Both[:40]
X_train_ada=pd.concat([X_train_minority,X_train_majority])
y_train_ada=pd.concat([Right,Both])
from imblearn.over_sampling import ADASYN
ada= ADASYN(sampling_strategy='minority',random_state=2,n_neighbors=5)
def confusion_matrix_ADASYN(X_train_ada,y_train_ada,X_test,y_test):
    X_train_ada, y_train_ada=ada.fit_resample(X_train_ada,y_train_ada)
    l=model.fit(X_train_ada, y_train_ada)
    print ('ADASYN result')
    y_pred_ada=l.predict(X_test)
    print(y_pred_ada) 
    conf_matrix_ada = confusion_matrix(y_true=y_test, y_pred=y_pred_ada)
    print('Confusion matrix ada:\n', conf_matrix_ada)
    kappa_ada= cohen_kappa_score(y_test,y_pred_ada, labels=None, weights='quadratic', sample_weight=None)
    print('kappa ada')
    print(kappa_ada)
    
print('Cross_validation')    
confusion_matrix_ADASYN(X_train,y_train,X_test,y_test)

Cross_validation
ADASYN result
[3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 3 2 3
 3 3 3 3 2 3 3 3 3 3 1 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 2 2
 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 1 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 2 3 2 3 3 3 3 2 3
 3 2 3 3 2 1 3 3 3 3 3 3 3 2 3 1 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 2 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 2 3 3 1 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 2 3 2 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 2 3 2 3 3 3 3 3 3 3 3 3 2 3 3 2 3 3 3 3 3 3 3 3 3 2 3 3 3 3
 3 3 3 2 3 3 3 2 3 3 3 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 2 3 3 3 3 3 3 3
 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 1 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 2 3 3 2 3 3 3 3 2 3 3 3 3 3 2 3 2 3 3 2 3 3 3 3 3 2 3 2
 3 2 2 3 3 3 3 3 3 3 3 2 3 3 3 1 3 3 3 3 3 3 1 3 3 2 3 3 3 3 3 3 3 3 3 3 3
 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 

In [51]:
#SVM
from sklearn import svm
svm = svm.SVC(kernel='linear', random_state=2)
def confusion_matrix_svm(X_train,y_train,X_test,y_test):
    svm.fit(X_train,y_train)
    print ('SVM result')
    y_pred_svm=svm.predict(X_test)
    print(y_pred_svm) 
    conf_mat_svm = confusion_matrix(y_true=y_test, y_pred=y_pred_svm)
    print('Confusion matrix svm:\n', conf_mat_svm)
    kappa_svm= cohen_kappa_score(y_test,y_pred_svm, labels=None, weights='quadratic', sample_weight=None)
    print('kappa svm')
    print(kappa_svm)
    
confusion_matrix_svm(X_train,y_train,X_test,y_test)

SVM result
[3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 2 3
 3 2 3 3 2 3 2 3 3 2 2 3 3 3 3 2 3 3 3 3 3 3 3 2 2 3 3 3 3 3 3 3 3 3 3 3 2
 3 3 3 3 3 2 3 3 3 3 3 3 2 2 3 3 3 3 3 3 3 3 3 2 2 3 3 3 3 3 3 2 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 2 2 3 3 3 3 3 3 2 2 3 3 3 2 3
 3 2 3 3 3 3 3 3 2 3 3 3 3 2 2 2 3 3 3 3 2 2 3 3 3 3 3 3 3 3 3 2 2 3 3 3 3
 3 3 3 2 3 3 3 3 3 3 3 3 2 3 3 2 2 3 3 3 3 3 2 2 3 3 3 3 3 3 2 3 3 3 3 3 3
 2 3 3 3 3 2 3 3 3 3 3 3 3 3 2 3 2 3 2 3 3 3 3 3 3 3 3 3 3 3 3 2 3 2 3 3 3
 3 3 3 2 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 2 3 3 3 3 2 3 3 2 3 2 3 3 3 3 3 2 3 3 2 3 3 2 3 3 3 3 3 3 3
 3 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 2 3 3 2 3 3 3 3 2 3 3 3 3 3 3 3 2 2 3 3 3 2 2 3 3 3 2 3 3 3 3 2 2 3 3 3
 3 2 2 2 2 3 2 3 3 3 3 2 2 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 3
 2 3 2 2 3 3 3 3 3 3 3 3 3 3 3 2 3 2 3 3 3 2 3 3 3 3 2 3 3 3 3 3 3 3 2 2 3
 3 3 2 3 3 3 3

In [37]:
#Bagging
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
cart = DecisionTreeClassifier()
def confusion_matrix_Bagging(X_train,y_train,X_test,y_test):
    Bagging = BaggingClassifier(base_estimator=cart, n_estimators=100, random_state=2)
    Bagging.fit(X_train,y_train)
    y_pred_Bagging=Bagging.predict(X_test)
    conf_mat_Bagging = confusion_matrix(y_true=y_test, y_pred=y_pred_Bagging)
    print('Confusion matrix Bagging:\n', conf_mat_Bagging)
    kappa_Bagging= cohen_kappa_score(y_test,y_pred_Bagging, labels=None, weights='quadratic', sample_weight=None)
    print('kappa Bagging')
    print(kappa_Bagging)
    
confusion_matrix_Bagging(X_train,y_train,X_test,y_test)

Confusion matrix Bagging:
 [[  0   4   9]
 [  0  55  64]
 [  0  38 332]]
kappa Bagging
0.33007537168956624


In [38]:
#Boosting
from sklearn.ensemble import GradientBoostingClassifier
Boosting=GradientBoostingClassifier(n_estimators=100, random_state=2)
def confusion_matrix_Boosting(X_train,y_train,X_test,y_test):
    Boosting.fit(X_train,y_train)
    y_pred_Boosting=Boosting.predict(X_test)
    conf_mat_Boosting = confusion_matrix(y_true=y_test, y_pred=y_pred_Boosting)
    print('Confusion matrix Boosting:\n', conf_mat_Boosting)
    kappa_Boosting= cohen_kappa_score(y_test,y_pred_Boosting, labels=None, weights='quadratic', sample_weight=None)
    print('kappa Boosting')
    print(kappa_Boosting)
    
print('Cross_validation')    
confusion_matrix_Boosting(X_train,y_train,X_test,y_test)

Cross_validation
Confusion matrix Boosting:
 [[  0   5   8]
 [  0  49  70]
 [  0  38 332]]
kappa Boosting
0.3090387864750441
